esphome:
  name: esphome-maybomnuoc
  comment: eshphome-maybomnuoc 18.10.2022
  project:
    name: "pnduyy.esphome-maybomnuoc"
    version: "1.0.9"
  on_boot:
    then:
      - script.execute: on_start

esp8266:
  board: esp01_1m
logger:
api:
ota:
  password: "0987654321234567890"
wifi:
  ssid: "IOT"
  password: "01102019"
  reboot_timeout: 0s
  #use upload code over wifi
  manual_ip:
    static_ip: 192.168.1.57
    gateway: 192.168.1.1
    subnet: 255.255.255.0
  ap:
    ssid: "Esphome-Maybomnuoc"
    password: "09876543"
captive_portal:
web_server:
  port: 80
###====================main=================================================================##  
text_sensor:
  - platform: wifi_info
    ip_address:
      name: "mbn11-IP Address"
    ssid:
      name: "mbn10-Wifi Connected"
#text để Hiển thị thời gian uptime
#text_sensor:
  - platform: template
    name: "mbn01-Uptime"
    id: uptime_human
    icon: mdi:clock-start
#Hiển thị thời gian local
  - platform: template
    name: "mbn02-Local Time"
    id: time_local
    update_interval: 60s
    lambda: |-
      auto time_text = id(maybomnuoc_time).now().strftime("%d/%m/%Y - %H:%M:%S");
      return { time_text };
switch:
  - platform: gpio
    pin: 2 #D4
    inverted: true
    name: "mbn22-led onboard"
    id: ledonboard
    on_turn_off:
      - switch.turn_off: ledonboard
    on_turn_on:
      - switch.turn_on: ledonboard
      - if:
          condition:
            - switch.is_on: err_30p
          then:
            - delay: 30min
            - switch.turn_off: relay_maybom

  - platform: gpio
    pin: 4 #D2
    #inverted: true
    name: "mbn23-Relay máy bơm"
    id: relay_maybom
  - platform: gpio
    pin: 0 #D3
    #inverted: true
    name: "mbn24-led night"
    id: led
  - platform: template
    id: err_30p
    name: "mbn-Tự động tắt máy bơm sau 30p"
    optimistic : true

    
binary_sensor:
##binary_sensor
##button: nhan 1 lan toggle maybom
##button: nhan double se mo may bom va sau 30p se tu tat maybom 
  - platform: gpio
    pin:
      number: 5 #D1
      inverted: true
      mode:
        input: true
        pullup: true
    name: "mbn25-bt_maybom"
    id: bt_maybom
    filters:
      - delayed_on_off: 100ms
    on_press:
      then:
        - switch.toggle: relay_maybom

 
# cảm biến mực nước        
  - platform: gpio
    pin:
      number: 14 #D5
      inverted: true
      mode:
        input: true
        pullup: true
    name: "mbn20-Bể nước - mức thấp"
    id: low_benuoc
  - platform: gpio
    pin:
      number: 13 #D7
      inverted: true
      mode:
        input: true
        pullup: true
    name: "mbn21-Bể nước - mức cao"
    id: high_benuoc
    on_press:
      then:
        - delay: 3s
        - if:
            condition:
              and:
                - switch.is_on: relay_maybom
                - binary_sensor.is_on: high_benuoc
                #- binary_sensor.is_on: low_benuoc
            then:
              - switch.turn_off: relay_maybom
interval:
  - interval: 5s
    then:
        - if:
            condition:
              and:
                - switch.is_off: relay_maybom
                - binary_sensor.is_off: low_benuoc
                - binary_sensor.is_off: high_benuoc
            then:
              - switch.turn_on: ledonboard
              - delay: 1s
              - switch.turn_off: ledonboard
  - interval: 1s
    then:
      - if:
          condition:
            - switch.is_on: relay_maybom
          then:
            - if:
                condition:
                  - switch.is_on: err_30p
                then:
                  - switch.toggle: ledonboard
                else:
                  - if:
                      condition:
                        - switch.is_off: ledonboard
                      then:
                        - switch.turn_on: ledonboard
          else:
            - if:
                condition:
                  or:
                    - binary_sensor.is_on: low_benuoc
                    - binary_sensor.is_on: high_benuoc
                then:
                  - if:
                      condition:
                        - switch.is_on: ledonboard
                      then:
                        - switch.turn_off: ledonboard

button:
#Khai bái button restart esphome
  - platform: restart
    name: "mbn03-Restart"
    
time:
  - platform: sntp
    timezone: "Asia/Ho_Chi_Minh"
    servers: 203.113.174.44
    id: maybomnuoc_time
    on_time:
      - cron: '0 0 19 * * *'
        then:
          - switch.turn_on: led
      - cron: '0 0 6 * * *'
        then:
          - switch.turn_off: led
    
sensor:
  - platform: wifi_signal
    name: "mbn12-Wifi signal connected"

#Tính toán thời gian uptime
#sensor:
  - platform: uptime
    name: "mbn00-Uptime sensor"
    id: uptime_sensor
    update_interval: 60s
    on_raw_value:
      then:
        - text_sensor.template.publish:
            id: uptime_human
            state: !lambda |-
              int seconds = round(id(uptime_sensor).raw_state);
              int days = seconds / (24 * 3600);
              seconds = seconds % (24 * 3600);
              int hours = seconds / 3600;
              seconds = seconds % 3600;
              int minutes = seconds /  60;
              seconds = seconds % 60;
              return (
                (days ? to_string(days) + "d " : "") +
                (hours ? to_string(hours) + "h " : "") +
                (minutes ? to_string(minutes) + "m " : "") +
                (to_string(seconds) + "s")
              ).c_str();  
##==========script=============
script:
  - id: on_start
    then:
      - switch.turn_off: relay_maybom
      - switch.turn_on: err_30p
      - repeat:
          count: 3
          then:
            - switch.turn_on: led
            - delay: 1s
            - switch.turn_off: led
            - delay: 1s
      - delay: 1min
      - if:
          condition:
            - lambda: >-
                return id(maybomnuoc_time).now().hour >= 6 && id(maybomnuoc_time).now().hour <= 19 ;
          then:
            - switch.turn_off: led
          else:
            - switch.turn_on: led
